### ISSUE TITLE
설치할때 설정한 호스트로접속을 할 수가 없습니다. 

### ISSUE THREAD

**Issue by easylogic** [tonite31/Imboard#1]
테스트를 해보고 있는 중인데요. 

node config.js  

에서 2 번 server 를 선택하고 

host 에 easylogic.co.kr  로 

적은 다음에 

http://easylogic.co.kr:3000/  으로 

브라우저에서 접속하면 아래와 같이 주소뒤에 호스트가 무한히 붙어버립니다. 

2번 서버 설정을 안했을 경우는 

localhost:3000 으로 바로 리다이렉틀 되버려서 사용할 수가 없네요. 

```

info: =================================================
info: time : Mon Sep 07 2015 10:57:56 GMT+0900 (KST)
info: url : /easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/
info: -------------------------------------------------
info:  # Request Headers #
info: host=easylogic.co.kr:3000
info: connection=keep-alive
info: accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
info: upgrade-insecure-requests=1
info: user-agent=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36
info: accept-encoding=gzip, deflate, sdch
info: accept-language=ko-KR,ko;q=0.8,en-US;q=0.6,en;q=0.4
info: cookie=connect.sid=s%3AASHhVSLfd9Jz8hTVvjgWIGm6-LRvKhOi.e9qkZJ0PQrJjp07jpN1lnO13X8m04rdoeFuikSa%2Fzvc
info: -------------------------------------------------
info:  # Request Parameters #
info: =================================================

=================================================
time : 2015-09-07 10:57:56
-------------------------------------------------
 # Select Sql - urlAuth.matchUrlAuth #
SELECT
                URL,
                LEVEL,
                USE_YN
        FROM
                IMB_URL_AUTH A
        WHERE
                ? REGEXP URL
-------------------------------------------------
 # parameters #
[ '/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/easylogic.co.kr/' ]
```

**Comment by tonite31** [comment]
호스트에 http://를 붙여보세요 http://easylogic.co.kr 로 입력해보세요

나의 iPhone에서 보냄
1. 9. 7. 오전 11:04 jinho park notifications@github.com 작성:

**Comment by easylogic** [comment]
현상에 똑같습니다.  

localhost 이외의 다른 걸 셋팅하면 주소 뒤에 설정된 호스트가 계속 붙어버리네요.

**Comment by tonite31** [comment]
메엘주신것 보고 검토를 해봤는데 host라는 단어가 적절치 않았던것 같습니다 ^^; 게다가 조금 고민해보면 그 정보는 입력하지 않아도 될것같군요.

일단 다음과같이 입력해보시기바랍니다.

http://easylogic.co.kr:3000

포트를 80외의 다른값으로 설정하셨다면 포트까지 입력해주세요.

이 부분은 빠른시일내에 업데이트를 하도록하겠습니다.

감사합니다

나의 iPhone에서 보냄
1. 9. 7. 오후 1:54 jinho park notifications@github.com 작성:

**Comment by easylogic** [comment]
2번 메뉴에서 

포트 3000
서버 공백

으로 설정했는데 이번에는 아무런 에러없이 화면이 똑같이 안나오네요.  ^^;;

**Comment by tonite31** [comment]
방금 0.3.0 버전으로 올렸습니다. imboard를 업데이트 하고 진행하시면 될것 같습니다.
2번 메뉴의 host정보는 더 이상 필요한 정보가 아니라서 삭제되었습니다.

**Comment by easylogic** [comment]
![image](https://cloud.githubusercontent.com/assets/591983/9709961/304985d2-556f-11e5-9d76-3135f059fa7f.png)

소스 업데이트 하고 다시 했는데요.. 

host 문제는 안나고 404 페이지만 뜹니다. 

최초 접속을 어떻게 해야할까요?

**Comment by tonite31** [comment]
content/frame/ 디렉토리 하위에 sample 디렉토리가 있어야하고 config 설정시 frame을 sample로 설정하셔야합니다.
또는 frame명을 변경하셨다면 변경한 이름과 일치하는 프레임이 frame폴더 하위에 있어야합니다.
이 부분을 확인해보시기 바랍니다.

**Comment by tonite31** [comment]
죄송합니다. 0.3.0 업데이트에서 빠뜨린 부분이 있었네요. 0.3.1 업데이트에 수정된 내용이 제대로 반영되었습니다.
업데이트를 하고 다시 진행해보시면 정상적으로 구동이 될겁니다.

**Comment by easylogic** [comment]
/settings 로 들어가지네요. 

최초 화면에서는 들어갈 수가 없군요. 

회원 등록 페이지도 404 나옵니다.

**Comment by tonite31** [comment]
회원 등록페이지는 아직 개발이 안되었습니다.. 그 버튼을 깜빡하고 그냥 놔뒀나보네요.
혹시 프레임은 sample로 구동하신것인가요?

**Comment by tonite31** [comment]
그리고 /settings, 관리자 대시보드와 로그인 화면쪽은 문서가 아직 작성되지 않았습니다.
최초 로그인은 관리자 계정으로 할 수 있으며 admin/admin 입니다.

**Comment by easylogic** [comment]
admin/admin 으로 들어가니  관리자 접속되고 
게시판 생성하니  메인도 들어가집니다.  ^^ 

위지윅 에디터도 붙이실 예정이신가요?

**Comment by tonite31** [comment]
ckeditor나 네이버, 다음의 에디터 등 특정 에디터에 의존하고 있는것이 아니기 때문에 원하는 위지윅 에디터를 프레임 개발자가 붙여서 배포하는게 컨셉입니다. 그래서 sample 프레임에는 위지윅 에디터를 붙일 생각은 없습니다.
sample 프레임은 말 그대로 임보드의 컨셉이나 기본적으로 어떻게 구동이되는지 보여주기위한 용도이기 때문입니다.

추후 블로그나 커뮤니티 사이트용 프레임에는 ckeditor를 붙여서 배포할 예정입니다.

개인적으로 개발중인 에디터가 있긴합니다만 올해 안에 오픈소스로 공개할 수 있을지는 모르겠네요^^;

**Comment by easylogic** [comment]
그렇군요. sample 은 각자 꾸미는 것이군요. ^^ 

bootstrap 기반이면 summernote 도 추천하고 싶지만 이미 만들고 계시다니 ^^ 

멋지게 만들어서 공유해주세요. ^^
