### ISSUE TITLE
게시판 글 보기 링크가 잘 못 된 것 같습니다. 

### ISSUE THREAD

**Issue by easylogic** [tonite31/Imboard#2]
글 보기 링크가 http://easylogic.co.kr:3000/?body=write&seq=1 

이렇게 나오는데요. 

boardId 가 빠져있어요. 

boardId=notice 형태로 추가 하셔야 할 것 같아요.

**Comment by tonite31** [comment]
그렇네요..^^; 나름 꽤 준비하고 글 썼다고 생각했는데 여러군데 오류가 많네요. 감사합니다.

**Comment by tonite31** [comment]
수정된 버전이 업데이트 되었습니다.

**Comment by easylogic** [comment]
잘 되네요. 수고하셨습니다. ^^
